import express from "express";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";

const PORT=Number(process.env.PORT||8787), NCBI="https://eutils.ncbi.nlm.nih.gov/entrez/eutils", TOOL="tmh-literature-chatgpt-app", EMAIL=process.env.NCBI_EMAIL||"";
const ROOT=dirname(dirname(fileURLToPath(import.meta.url)));
const LIB={proxyHost:"www.scmhem.org.tw",proxyPort:3001,ermJournalUrl:"https://www.scmhem.org.tw/scmherm/sendurl_api_v3.jsp?type=0&journal_id=",ermDetailUrl:"https://www.scmhem.org.tw/scmherm/detail_source.jsp?esource_classify=databases&id=",ermDbUrl:"https://www.scmhem.org.tw/scmherm/sendurl_api_v3.jsp?dbid=",activateUrl:"https://www.scmhem.org.tw/scmherm/sendurl_api_v3.jsp?type=0&journal_id=27992"};
const PLAT_NOTE={C:"ClinicalKey 【電子期刊&電子書】",O:"OVID 【電子期刊】",M:"MEDLINE電子期刊",P:"ProQuest 【電子期刊】",S:"Springer 【電子期刊】",W:"Wiley Online Library(電子期刊)",D:"ScienceDirect(SDOL)",A:"Airiti Library 【華藝中文電子期刊】",N:"南醫單本訂購期刊",X:"Open Access",Y:"其它"};
const PLATFORM=[[/medline|ebsco/i,"EBSCO MEDLINE","LDB0074"],[/cochrane/i,"Cochrane Library","LDB0009"],[/clinicalkey/i,"ClinicalKey","LDB0165"],[/ovid/i,"Ovid","LDB0167"],[/proquest/i,"ProQuest","LDB0168"],[/wiley/i,"Wiley","LDB0006"],[/springer/i,"Springer","LDB0138"],[/sciencedirect/i,"ScienceDirect","DB81005"],[/airiti|華藝/i,"Airiti Library","LDB0164"]];
const OA_PREFIXES=["10.1186/","10.1371/","10.3389/","10.3390/","10.7717/","10.1101/","10.7759/","10.2196/","10.12688/","10.1155/","10.1038/s41598","10.1136/bmjopen"];
const PUB_MAP=[[/^10\.1056\//i,d=>`https://www.nejm.org/doi/full/${d}`],[/^10\.1002\/14651858/i,d=>`https://www.cochranelibrary.com/cdsr/doi/${d}/full`],[/^10\.(1002|1111)\//i,d=>`https://onlinelibrary.wiley.com/doi/${d}`],[/^10\.1007\//i,d=>`https://link.springer.com/article/${d}`],[/^10\.1038\//i,d=>`https://www.nature.com/articles/${d.replace(/^10\.1038\//i,"")}`],[/^10\.1161\//i,d=>`https://www.ahajournals.org/doi/${d}`],[/^10\.1177\//i,d=>`https://journals.sagepub.com/doi/${d}`],[/^10\.1080\//i,d=>`https://www.tandfonline.com/doi/${d}`],[/^10\.1200\//i,d=>`https://ascopubs.org/doi/${d}`],[/^10\.1164\//i,d=>`https://www.atsjournals.org/doi/${d}`],[/^10\.1212\//i,d=>`https://www.neurology.org/doi/${d}`],[/^10\.1128\//i,d=>`https://journals.asm.org/doi/${d}`],[/^10\.7326\//i,d=>`https://www.acpjournals.org/doi/${d}`],[/^10\.1146\//i,d=>`https://www.annualreviews.org/doi/${d}`]];
const normTitle=s=>String(s||"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/\([^)]*\)|\[[^\]]*\]/g,"").replace(/,\s*(the|a|an)\s*$/,"").replace(/&/g," and ").trim().replace(/^the\s+/,"").replace(/[^a-z0-9\u4e00-\u9fff]+/g,"");
const titleKeys=s=>[...new Set([normTitle(s),...String(s||"").split(/[:;]/).map(normTitle).filter(x=>x.length>=4)])];
const holdings=(()=>{const byTitle=new Map();let count=0;const add=(k,e)=>{if(!k)return;if(!byTitle.has(k))byTitle.set(k,[]);byTitle.get(k).push(e)};for(const line of readFileSync(join(ROOT,"data/holdings.txt"),"utf8").split("\n")){const f=line.split("|");if(f.length<4||!f[0])continue;const e={title:f[0],from:+f[2]||0,to:+f[3]||0,note:PLAT_NOTE[f[1]]||f[1],jid:f[4]||""};count++;titleKeys(e.title).forEach(k=>add(k,e))}return{count,byTitle}})();
function eutil(name,params){const u=new URL(`${NCBI}/${name}.fcgi`),all={...params,tool:TOOL};if(EMAIL)all.email=EMAIL;for(const[k,v]of Object.entries(all))u.searchParams.set(k,String(v));return u}
function decodeXml(s=""){return s.replace(/<[^>]+>/g," ").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim()}
const first=(b,re)=>{const m=b.match(re);return m?decodeXml(m[1]):""}, all=(b,re)=>[...b.matchAll(re)].map(m=>decodeXml(m[1])).filter(Boolean);
function parsePubmedXml(xml){return[...xml.matchAll(/<PubmedArticle>([\s\S]*?)<\/PubmedArticle>/g)].map(m=>m[1]).map(a=>{const pmid=first(a,/<PMID[^>]*>([\s\S]*?)<\/PMID>/),title=first(a,/<ArticleTitle[^>]*>([\s\S]*?)<\/ArticleTitle>/),journal=first(a,/<Journal>[\s\S]*?<Title>([\s\S]*?)<\/Title>/),year=first(a,/<PubDate>[\s\S]*?<Year>([\s\S]*?)<\/Year>/)||first(a,/<ArticleDate[^>]*>[\s\S]*?<Year>([\s\S]*?)<\/Year>/),authors=[...a.matchAll(/<Author\b[^>]*>([\s\S]*?)<\/Author>/g)].map(m=>{const b=m[1];return first(b,/<CollectiveName>([\s\S]*?)<\/CollectiveName>/)||[first(b,/<ForeName>([\s\S]*?)<\/ForeName>/),first(b,/<LastName>([\s\S]*?)<\/LastName>/)].filter(Boolean).join(" ")}).filter(Boolean),id=t=>first(a,new RegExp(`<ArticleId IdType=["']${t}["']>([\\s\\S]*?)<\\/ArticleId>`,'i')),doi=id("doi"),pmc=id("pmc"),pii=id("pii"),issn=first(a,/<ISSN[^>]*>([\s\S]*?)<\/ISSN>/);return{pmid,title,journal,journalFull:journal,year,authors,abstract:all(a,/<AbstractText[^>]*>([\s\S]*?)<\/AbstractText>/g).join("\n\n"),doi,pmc,pii,issn,mesh:all(a,/<DescriptorName[^>]*>([\s\S]*?)<\/DescriptorName>/g).slice(0,12),pubmed_url:pmid?`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`:"",doi_url:doi?`https://doi.org/${doi}`:""}})}
async function fetchArticles(ids){if(!ids.length)return[];const r=await fetch(eutil("efetch",{db:"pubmed",id:ids.join(","),retmode:"xml",rettype:"abstract"}));if(!r.ok)throw new Error(`PubMed EFetch HTTP ${r.status}`);return parsePubmedXml(await r.text())}
async function searchPubMed(query,maxResults=10,sort="relevance",retstart=0){const r=await fetch(eutil("esearch",{db:"pubmed",term:query,retmax:maxResults,retstart,retmode:"json",sort}));if(!r.ok)throw new Error(`PubMed ESearch HTTP ${r.status}`);const e=(await r.json()).esearchresult,ids=e?.idlist||[];return{query,count:Number(e?.count||0),translation:e?.querytranslation||"",retstart,articles:await fetchArticles(ids)}}
async function getArticle(pmid){return(await fetchArticles([pmid]))[0]||null}
const isAgg=e=>/ovid|proquest|ebsco|cinahl|airiti|華藝|clinicalkey|medline|cochrane|dynamed/i.test(e?.note||""), rank=e=>/sciencedirect/i.test(e.note||"")?2.5:!isAgg(e)?0:/clinicalkey/i.test(e.note)?1:/medline|ebsco|ovid/i.test(e.note)?2:3;
function holdingFor(rec){let list=null;for(const k of titleKeys(rec.journalFull||rec.journal)){if(k&&holdings.byTitle.has(k)){list=holdings.byTitle.get(k);break}}if(!list)return{status:"no"};const y=+rec.year||0,covered=list.filter(e=>!y||((!e.from||y>=e.from)&&(!e.to||y<=e.to))).sort((a,b)=>rank(a)-rank(b)),range=e=>(e.from||e.to)?`${e.from||""}–${e.to||"今"}`:"";if(covered.length)return{status:"yes",entry:covered[0],range:range(covered[0]),alts:covered.slice(1)};const e=list[0];return{status:"partial",entry:e,range:range(e),alts:[]}}
const proxyBase=()=>`https://${LIB.proxyHost}:${LIB.proxyPort}`, loginUrlFor=t=>`${proxyBase()}/login?url=${encodeURIComponent(t)}`, ermJournal=e=>e?.jid?LIB.ermJournalUrl+encodeURIComponent(e.jid):"", isElsevier=d=>/^10\.(1016|1053|1054|1067|1078|1157|1529|3816)\//i.test(d||""), publisher=rec=>{for(const[re,fn]of PUB_MAP)if(re.test(rec.doi||""))return fn(rec.doi);return rec.doi?`https://doi.org/${rec.doi}`:rec.pubmed_url}, ck=rec=>rec.pii?`https://www.clinicalkey.com/#!/content/playContent/1-s2.0-${String(rec.pii).replace(/[^A-Za-z0-9]/g,"")}`:"";
function platformInfo(e){const p=PLATFORM.find(([re])=>re.test(e?.note||""));return p?{name:p[1],dbid:p[2],detail_url:LIB.ermDetailUrl+p[2]}:null}
function resolveLibrary(rec){const h=holdingFor(rec),doi=rec.doi||"",pm=rec.pubmed_url||`https://pubmed.ncbi.nlm.nih.gov/${rec.pmid}/`;if(rec.pmc)return{holding:h,route:"pmc",url:`https://pmc.ncbi.nlm.nih.gov/articles/${rec.pmc}/`,free:true};if(doi&&OA_PREFIXES.some(p=>doi.toLowerCase().startsWith(p)))return{holding:h,route:"open_access",url:`https://doi.org/${doi}`,free:true};let kind="article",entry=h.entry;if(h.status!=="no"&&entry&&isAgg(entry)){if(/medline|ebsco/i.test(entry.note)&&rec.pmid)kind="ebsco";else if(/ovid/i.test(entry.note)&&doi)kind="ovid";else if(/clinicalkey/i.test(entry.note)&&rec.pii)kind="clinicalkey";else if(ermJournal(entry))kind="erm"}else if(/^10\.1097\//i.test(doi))kind="ovid";else if(isElsevier(doi)&&rec.pii)kind="clinicalkey";let target;if(kind==="erm")target=ermJournal(entry);else if(kind==="ebsco")target=loginUrlFor(`https://search.ebscohost.com/login.aspx?direct=true&db=mnh&AN=${encodeURIComponent(rec.pmid)}&site=ehost-live&scope=site`);else if(kind==="ovid")target=loginUrlFor(`https://ovidsp.ovid.com/ovidweb.cgi?T=JS&MODE=ovid&NEWS=n&CSC=Y&PAGE=fulltext&D=ovft&SEARCH=%22${encodeURIComponent(doi)}%22.do`);else if(kind==="clinicalkey")target=loginUrlFor(ck(rec));else if(entry&&/sciencedirect/i.test(entry.note)&&rec.pii)target=loginUrlFor(`https://www.sciencedirect.com/science/article/pii/${String(rec.pii).replace(/[^A-Za-z0-9]/g,"")}`);else target=doi?loginUrlFor(publisher(rec)):pm;return{holding:h,route:kind,url:target,free:false,platform:platformInfo(entry),erm_journal_url:ermJournal(entry),activate_library_url:LIB.activateUrl,ndds_url:"https://ndds.stpi.niar.org.tw/"}}
async function oaLookup(doi){if(!doi)return null;try{const u=new URL("https://api.openalex.org/works");u.searchParams.set("filter",`doi:${doi.toLowerCase()}`);u.searchParams.set("select","doi,open_access");if(EMAIL)u.searchParams.set("mailto",EMAIL);const r=await fetch(u);if(!r.ok)return null;const w=(await r.json()).results?.[0],oa=w?.open_access;return oa?.is_oa?{is_oa:true,url:oa.oa_url||"",status:oa.oa_status||""}:{is_oa:false}}catch{return null}}
function createServer(){const s=new McpServer({name:"台南市立醫院找文獻",version:"1.0.0"});
 s.registerTool("search_pubmed",{title:"搜尋 PubMed",description:"依臨床問題產生的 PubMed/MeSH 查詢式搜尋文獻。可分頁，回傳摘要、DOI、PMCID、PII、MeSH，並附本院館藏路由。",inputSchema:{query:z.string().min(2),max_results:z.number().int().min(1).max(20).default(10),sort:z.enum(["relevance","pub_date"]).default("relevance"),retstart:z.number().int().min(0).default(0)},annotations:{readOnlyHint:true,openWorldHint:true},_meta:{"openai/outputTemplate":"ui://tmh-literature/results.html"}},async a=>{const r=await searchPubMed(a.query,a.max_results,a.sort,a.retstart);r.articles=r.articles.map(x=>({...x,library:resolveLibrary(x)}));return{content:[{type:"text",text:`PubMed 找到 ${r.count} 筆。請以回傳摘要為證據，先回答臨床問題，再列 PICO、檢索式、主要研究與限制；不要虛構未回傳內容。`}],structuredContent:r}});
 s.registerTool("get_pubmed_article",{title:"取得 PubMed 單篇",description:"依 PMID 取得完整書目、摘要、MeSH、DOI 與本院全文入口。",inputSchema:{pmid:z.string().regex(/^\d+$/)},annotations:{readOnlyHint:true,openWorldHint:true}},async({pmid})=>{const a=await getArticle(pmid);return{content:[{type:"text",text:a?JSON.stringify(a):`找不到 PMID ${pmid}`}],structuredContent:{article:a?{...a,library:resolveLibrary(a)}:null}}});
 s.registerTool("check_tmh_holdings",{title:"查台南市立醫院館藏",description:"依 PMID 查本院 2026-09 ERM 內嵌館藏，判斷收錄狀態、平台、涵蓋年份與期刊入口。",inputSchema:{pmid:z.string().regex(/^\d+$/)},annotations:{readOnlyHint:true,openWorldHint:true}},async({pmid})=>{const a=await getArticle(pmid);const result=a?resolveLibrary(a):null;return{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:{article:a,result,holdings_count:holdings.count}}});
 s.registerTool("resolve_tmh_fulltext",{title:"取得本院全文入口",description:"依 PMID 產生 PMC、ClinicalKey、EBSCO、Ovid、ScienceDirect、ERM 或出版社代理登入入口；不保存任何院內帳密。",inputSchema:{pmid:z.string().regex(/^\d+$/)},annotations:{readOnlyHint:true,openWorldHint:true}},async({pmid})=>{const a=await getArticle(pmid),result=a?resolveLibrary(a):null;return{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:{article:a,result}}});
 s.registerTool("find_free_fulltext",{title:"找合法免費全文",description:"依 PMID/DOI 查 PMC 與 OpenAlex open-access 資訊。",inputSchema:{pmid:z.string().optional(),doi:z.string().optional()},annotations:{readOnlyHint:true,openWorldHint:true}},async({pmid,doi})=>{let a=pmid?await getArticle(pmid):null;doi=doi||a?.doi||"";const result=a?.pmc?{is_oa:true,url:`https://pmc.ncbi.nlm.nih.gov/articles/${a.pmc}/`,source:"PMC"}:await oaLookup(doi);return{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:{result}}});
 s.registerTool("library_help",{title:"圖書館全文使用說明",description:"回傳本院遠端連線啟用、ERM、館際合作與館藏版本資訊。",inputSchema:{},annotations:{readOnlyHint:true,openWorldHint:true}},async()=>{const result={holdings_version:"2026-09",holdings_count:holdings.count,activate_library_url:LIB.activateUrl,erm_home:"https://www.scmhem.org.tw/scmherm/index.jsp",ndds_url:"https://ndds.stpi.niar.org.tw/",note:"本 App 不保存任何圖書館帳號密碼；遠端授權與共用帳密由本院 ERM 處理。"};return{content:[{type:"text",text:JSON.stringify(result)}],structuredContent:result}});
 s.registerResource("tmh-results-ui","ui://tmh-literature/results.html",{title:"找文獻結果",description:"PubMed 與本院全文結果卡片",mimeType:"text/html+skybridge"},async()=>({contents:[{uri:"ui://tmh-literature/results.html",mimeType:"text/html+skybridge",text:RESULTS_UI}]}));return s}
const RESULTS_UI=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui,-apple-system,sans-serif;margin:0;padding:12px;color:#17202a;background:#fff}.head{display:flex;justify-content:space-between;gap:12px;margin-bottom:10px}.q,.title{font-weight:700}.count,.meta,.tag{font-size:12px;color:#667085}.card{border:1px solid #e4e7ec;border-radius:12px;padding:12px;margin:8px 0}.abs{font-size:13px;line-height:1.5;display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden;margin:7px 0}.tag{display:inline-block;background:#f2f4f7;border-radius:999px;padding:2px 7px;margin:2px}.links a{font-size:12px;margin-right:10px}</style></head><body><div id="app">載入中…</div><script>function e(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}function render(d){let a=d?.articles||[];document.querySelector('#app').innerHTML='<div class="head"><div class="q">'+e(d?.query||'PubMed')+'</div><div class="count">共 '+(d?.count||0)+' 筆</div></div>'+a.map(x=>{let l=x.library||{},h=l.holding||{},label=h.status==='yes'?'本院有館藏':h.status==='partial'?'部分年份':'館藏未列';return '<div class="card"><div class="title">'+e(x.title)+'</div><div class="meta">'+e([x.journal,x.year,(x.authors||[]).slice(0,3).join(', ')].filter(Boolean).join(' · '))+'</div><span class="tag">'+e(label+(h.range?' '+h.range:''))+'</span>'+(l.platform?'<span class="tag">'+e(l.platform.name)+'</span>':'')+'<div class="abs">'+e(x.abstract||'無摘要')+'</div><div class="links">'+(x.pubmed_url?'<a href="'+x.pubmed_url+'" target="_blank">PubMed</a>':'')+(l.url?'<a href="'+l.url+'" target="_blank">圖書館全文</a>':'')+(x.doi_url?'<a href="'+x.doi_url+'" target="_blank">DOI</a>':'')+'</div></div>'}).join('')}window.addEventListener('message',ev=>{let d=ev.data;if(d?.type==='openai:set_globals'||d?.type==='openai:setGlobals')render(d.globals?.toolOutput||d.globals?.tool_output)});render(window.openai?.toolOutput||window.openai?.tool_output||{});</script></body></html>`;
const app=express();app.use(express.json({limit:"2mb"}));const transports=new Map();app.all("/mcp",async(req,res)=>{try{const sid=req.headers["mcp-session-id"];let t=sid?transports.get(sid):undefined;if(!t){const server=createServer();t=new StreamableHTTPServerTransport({sessionIdGenerator:()=>randomUUID(),onsessioninitialized:id=>transports.set(id,t)});t.onclose=()=>{if(t.sessionId)transports.delete(t.sessionId)};await server.connect(t)}await t.handleRequest(req,res,req.body)}catch(err){console.error(err);if(!res.headersSent)res.status(500).json({jsonrpc:"2.0",error:{code:-32603,message:String(err?.message||err)},id:null})}});app.get("/health",(_q,r)=>r.json({ok:true,holdings:holdings.count,version:"1.0.0"}));app.get("/",(_q,r)=>r.type("text").send("TMH Literature ChatGPT App MCP v1.0 — use /mcp"));app.listen(PORT,()=>console.log(`TMH Literature MCP listening on http://localhost:${PORT}/mcp — ${holdings.count} holdings loaded`));
